update cache on every commit

diff --git a/.github/workflows/pkg.yaml b/.github/workflows/pkg.yaml
--- a/.github/workflows/pkg.yaml
+++ b/.github/workflows/pkg.yaml
@@ -23,45 +23,51 @@ env:
       github.ref_type == 'tag'
     }}
 
+  build_and_cache: |-
+    build_and_cache() {
+      arch="$1"
+      if ! docker buildx build \
+        --platform linux/$arch \
+        --cache-from type=local,src=/home/runner/tmp/$arch \
+        --cache-to type=local,dest=/home/runner/tmp/$arch \
+        --tag ${GITHUB_REPOSITORY,,}:$arch \
+        --file Dockerfile . ;
+      then
+        echo "::error::Docker-Build Error. $arch Cache will be deleted now!"
+        rm -rf /home/runner/tmp/$arch/
+      fi
+    }
+
 jobs:
   build:
     name: Build
     runs-on: ubuntu-latest
     steps:
-
       - name: Checkout
         uses: actions/checkout@master
-  
-      - name: Cache docker buildx
-        uses: actions/cache@v2
+
+      - name: update cache on every commit
+        uses: actions/cache@v3
         with:
-          path: |
-            /home/runner/tmp
-          key: docker-tmp
+          path: /home/runner/tmp
+          key: docker-${{ github.run_id }}
+          restore-keys: |
+            docker-
 
       - name: Prep build # also builds the conatiner when triggered via workflow_dispatch
-        run: | 
+        run: |
           docker buildx create --use
           docker buildx inspect --bootstrap
 
+      - name: Fill cache
+        run: |
+          ${{ env.build_and_cache }} 
+          build_and_cache amd64
 
-      - name: Fill AMD64 cache
+      - name: Fill ARM64 cache
         run: |
-          docker buildx build \
-          --platform linux/amd64 \
-          --cache-from type=local,src=/home/runner/tmp/amd64 \
-          --cache-to type=local,dest=/home/runner/tmp/amd64 \
-          --tag ${GITHUB_REPOSITORY,,}:amd64 \
-          --file Dockerfile .
-      
-      - name: Fill ARM cache
-        run: |
-          docker buildx build \
-          --platform linux/arm64 \
-          --cache-from type=local,src=/home/runner/tmp/arm64 \
-          --cache-to type=local,dest=/home/runner/tmp/arm64 \
-          --tag ${GITHUB_REPOSITORY,,}:arm64 \
-          --file Dockerfile .
+          ${{ env.build_and_cache }} 
+          build_and_cache arm64
         
       - name: Login container registry
         if: fromJSON(env.should_push_image)
